// 内置常用镜像logo配置
// 格式: { "镜像名称": "logo URL" }
// 支持镜像名称匹配，如 "nginx" 会匹配 "nginx:latest", "nginx:alpine" 等

export const builtInImageLogos = {
  // 常用Docker镜像
  "nginx": "https://icon.xiaoge.org/images/docker/Nginx.png",
  "mysql": "https://icon.xiaoge.org/images/docker/MySQL.png",
  "redis": "https://icon.xiaoge.org/images/docker/Redis.png",
  "postgres": "https://icon.xiaoge.org/images/docker/PostgreSQL.png",
  "mariadb": "https://icon.xiaoge.org/images/docker/MariaDB.png",
  "mongodb": "https://icon.xiaoge.org/images/docker/MongoDB.png",
  "node": "https://icon.xiaoge.org/images/docker/Node.png",
  "python": "https://icon.xiaoge.org/images/docker/Python.png",
  "php": "https://icon.xiaoge.org/images/docker/PHP.png",
  "java": "https://icon.xiaoge.org/images/docker/Java.png",
  "golang": "https://icon.xiaoge.org/images/docker/Go.png",
  "ruby": "https://icon.xiaoge.org/images/docker/Ruby.png",
  "alpine": "https://icon.xiaoge.org/images/nas/Alpine.png",
  "ubuntu": "https://icon.xiaoge.org/images/nas/Ubuntu.png",
  "debian": "https://icon.xiaoge.org/images/nas/Debian.png",
  "centos": "https://icon.xiaoge.org/images/nas/CentOS.png",
  
  // 常用应用镜像
  "wordpress": "https://icon.xiaoge.org/images/docker/WordPress.png",
  "nextcloud": "https://icon.xiaoge.org/images/docker/Nextcloud.png",
  "ghost": "https://icon.xiaoge.org/images/docker/Ghost.png",
  "joomla": "https://icon.xiaoge.org/images/docker/Joomla.png",
  "drupal": "https://icon.xiaoge.org/images/docker/Drupal.png",
  "jenkins": "https://icon.xiaoge.org/images/docker/Jenkins.png",
  "gitlab": "https://icon.xiaoge.org/images/docker/GitLab.png",
  "grafana": "https://icon.xiaoge.org/images/docker/Grafana.png",
  "prometheus": "https://icon.xiaoge.org/images/docker/Prometheus.png",
  "elasticsearch": "https://icon.xiaoge.org/images/docker/Elasticsearch.png",
  "kibana": "https://icon.xiaoge.org/images/docker/Kibana.png",
  "rabbitmq": "https://icon.xiaoge.org/images/docker/RabbitMQ.png",
  "memcached": "https://icon.xiaoge.org/images/docker/Memcached.png",
  "influxdb": "https://icon.xiaoge.org/images/docker/InfluxDB.png",
  "portainer": "https://icon.xiaoge.org/images/docker/Portainer.png",
  "traefik": "https://icon.xiaoge.org/images/docker/Traefik.png",
  "registry": "https://icon.xiaoge.org/images/docker/Registry.png",
  "busybox": "https://icon.xiaoge.org/images/docker/BusyBox.png",
  
  // 1Panel相关镜像
  "1panel": "https://icon.xiaoge.org/images/docker/1panel.png",
  "1panel/1panel": "https://icon.xiaoge.org/images/docker/1panel.png",
  "1panel/pro": "https://icon.xiaoge.org/images/docker/1panel-Pro.png",
  
  // 媒体相关镜像
  "emby": "https://icon.xiaoge.org/images/docker/Emby.png",
  "jellyfin": "https://icon.xiaoge.org/images/docker/Jellyfin.png",
  "plex": "https://icon.xiaoge.org/images/docker/Plex.png",
  "transmission": "https://icon.xiaoge.org/images/docker/Transmission.png",
  "qbittorrent": "https://icon.xiaoge.org/images/docker/qBittorrent.png",
  "jackett": "https://icon.xiaoge.org/images/docker/Jackett.png",
  "sonarr": "https://icon.xiaoge.org/images/docker/Sonarr.png",
  "radarr": "https://icon.xiaoge.org/images/docker/Radarr.png",
  "lidarr": "https://icon.xiaoge.org/images/docker/Lidarr.png",
  "readarr": "https://icon.xiaoge.org/images/docker/Readarr.png",
  
  // 网络和工具镜像
  "adguardhome": "https://icon.xiaoge.org/images/docker/AdguardHome.png",
  "alist": "https://icon.xiaoge.org/images/docker/Alist.png",
  "bitwarden": "https://icon.xiaoge.org/images/docker/Bitwarden.png",
  "vaultwarden": "https://icon.xiaoge.org/images/docker/Vaultwarden.png",
  "uptimekuma": "https://icon.xiaoge.org/images/docker/UptimeKuma.png",
  "heimdall": "https://icon.xiaoge.org/images/docker/Heimdall.png",
  "filebrowser": "https://icon.xiaoge.org/images/docker/FileBrowser.png",
  "phpmyadmin": "https://icon.xiaoge.org/images/docker/phpMyAdmin.png",
  "adminer": "https://icon.xiaoge.org/images/docker/Adminer.png",
  
  // 开发工具镜像
  "vscode": "https://icon.xiaoge.org/images/docker/VSCode.png",
  "code-server": "https://icon.xiaoge.org/images/docker/VSCode.png",
  "git": "https://icon.xiaoge.org/images/website/GitHub.png",
  "svn": "https://icon.xiaoge.org/images/docker/SVN.png",
  
  // 消息和聊天应用
  "mattermost": "https://icon.xiaoge.org/images/docker/Mattermost.png",
  "rocketchat": "https://icon.xiaoge.org/images/docker/RocketChat.png",
  "matrix": "https://icon.xiaoge.org/images/docker/Matrix.png",
  "element": "https://icon.xiaoge.org/images/docker/Element.png",
  
  // 云服务商相关镜像
  "aliyun": "https://icon.xiaoge.org/images/cloud/Aliyun.png",
  "huawei": "https://icon.xiaoge.org/images/cloud/Huawei.png",
  "qcloud": "https://icon.xiaoge.org/images/cloud/Qcloud.png",
  "oracle": "https://icon.xiaoge.org/images/cloud/Oracle.png",
  "googlecloud": "https://icon.xiaoge.org/images/cloud/GoogleCloud.png",
  "aws": "https://icon.xiaoge.org/images/cloud/AWS.png",
  "azure": "https://icon.xiaoge.org/images/cloud/Azure.png",
  
  // 其他常用镜像
  "docker": "https://icon.xiaoge.org/images/website/Docker.png",
  "dockercopilot": "https://icon.xiaoge.org/images/docker/DockerCopilot.png",
  "dockge": "https://icon.xiaoge.org/images/docker/Dockge.png",
  "homeassistant": "https://icon.xiaoge.org/images/docker/HomeAssistant.png",
  "homebridge": "https://icon.xiaoge.org/images/docker/HomeBridge.png",
  "openvpn": "https://icon.xiaoge.org/images/docker/OpenVPN.png",
  "wireguard": "https://icon.xiaoge.org/images/docker/WireGuard.png",
  "tailscale": "https://icon.xiaoge.org/images/docker/Tailscale.png",
  "pi-hole": "https://icon.xiaoge.org/images/docker/PiHole.png",
  "pihole": "https://icon.xiaoge.org/images/docker/PiHole.png",
  "unbound": "https://icon.xiaoge.org/images/docker/Unbound.png",
  "dnsmasq": "https://icon.xiaoge.org/images/docker/Dnsmasq.png",
  
  // 数据库管理工具
  "pgadmin": "https://icon.xiaoge.org/images/docker/PgAdmin.png",
  "adminmongo": "https://icon.xiaoge.org/images/docker/AdminMongo.png",
  "mongodb-express": "https://icon.xiaoge.org/images/docker/MongoExpress.png",
  "redis-commander": "https://icon.xiaoge.org/images/docker/RedisCommander.png",
  "redisinsight": "https://icon.xiaoge.org/images/docker/RedisInsight.png",
  
  // 监控和日志
  "prometheus": "https://icon.xiaoge.org/images/docker/Prometheus.png",
  "grafana": "https://icon.xiaoge.org/images/docker/Grafana.png",
  "loki": "https://icon.xiaoge.org/images/docker/Loki.png",
  "promtail": "https://icon.xiaoge.org/images/docker/Promtail.png",
  "jaeger": "https://icon.xiaoge.org/images/docker/Jaeger.png",
  "zipkin": "https://icon.xiaoge.org/images/docker/Zipkin.png",
  
  // 消息队列
  "rabbitmq": "https://icon.xiaoge.org/images/docker/RabbitMQ.png",
  "kafka": "https://icon.xiaoge.org/images/docker/Kafka.png",
  "nats": "https://icon.xiaoge.org/images/docker/NATS.png",
  "redis": "https://icon.xiaoge.org/images/docker/Redis.png",
  
  // 存储和文件服务
  "minio": "https://icon.xiaoge.org/images/docker/MinIO.png",
  "nextcloud": "https://icon.xiaoge.org/images/docker/Nextcloud.png",
  "owncloud": "https://icon.xiaoge.org/images/docker/OwnCloud.png",
  "seafile": "https://icon.xiaoge.org/images/docker/Seafile.png",
  "syncthing": "https://icon.xiaoge.org/images/docker/Syncthing.png",
  "resilio": "https://icon.xiaoge.org/images/docker/Resilio.png",
  
  // Web服务器和代理
  "nginx": "https://icon.xiaoge.org/images/docker/Nginx.png",
  "apache": "https://icon.xiaoge.org/images/docker/Apache.png",
  "caddy": "https://icon.xiaoge.org/images/docker/Caddy.png",
  "traefik": "https://icon.xiaoge.org/images/docker/Traefik.png",
  "haproxy": "https://icon.xiaoge.org/images/docker/HAProxy.png",
  "envoy": "https://icon.xiaoge.org/images/docker/Envoy.png",
  
  // 容器编排
  "kubernetes": "https://icon.xiaoge.org/images/docker/Kubernetes.png",
  "docker": "https://icon.xiaoge.org/images/website/Docker.png",
  "podman": "https://icon.xiaoge.org/images/docker/Podman.png",
  "containerd": "https://icon.xiaoge.org/images/docker/Containerd.png",
  
  // 安全和认证
  "vault": "https://icon.xiaoge.org/images/docker/Vault.png",
  "keycloak": "https://icon.xiaoge.org/images/docker/Keycloak.png",
  "authelia": "https://icon.xiaoge.org/images/docker/Authelia.png",
  "oauth2-proxy": "https://icon.xiaoge.org/images/docker/OAuth2Proxy.png",
  
  // 其他工具
  "curl": "https://icon.xiaoge.org/images/docker/Curl.png",
  "wget": "https://icon.xiaoge.org/images/docker/Wget.png",
  "ssh": "https://icon.xiaoge.org/images/docker/SSH.png",
  "telnet": "https://icon.xiaoge.org/images/docker/Telnet.png",
  "ping": "https://icon.xiaoge.org/images/docker/Ping.png",
  "traceroute": "https://icon.xiaoge.org/images/docker/Traceroute.png",
  
  // 备份和同步
  "borg": "https://icon.xiaoge.org/images/docker/Borg.png",
  "restic": "https://icon.xiaoge.org/images/docker/Restic.png",
  "duplicati": "https://icon.xiaoge.org/images/docker/Duplicati.png",
  "duplicity": "https://icon.xiaoge.org/images/docker/Duplicity.png",
  
  // 网络工具
  "iperf": "https://icon.xiaoge.org/images/docker/Iperf.png",
  "speedtest": "https://icon.xiaoge.org/images/docker/Speedtest.png",
  "netdata": "https://icon.xiaoge.org/images/docker/Netdata.png",
  "glances": "https://icon.xiaoge.org/images/docker/Glances.png",
  "htop": "https://icon.xiaoge.org/images/docker/Htop.png",
  "iftop": "https://icon.xiaoge.org/images/docker/Iftop.png",
  
  // 其他云服务商（保留部分）
  "bandwagon": "https://icon.xiaoge.org/images/cloud/Bandwagon.png",
  "buyvm": "https://icon.xiaoge.org/images/cloud/BuyVM.png",
  "bytevirt": "https://icon.xiaoge.org/images/cloud/ByteVirt.png",
  "cloudcone": "https://icon.xiaoge.org/images/cloud/CloudCone.png",
  "dmit": "https://icon.xiaoge.org/images/cloud/DMIT.png",
  "greencloud": "https://icon.xiaoge.org/images/cloud/Greencloud.png",
  "hosthatch": "https://icon.xiaoge.org/images/cloud/Hosthatch.png",
  "racknerd": "https://icon.xiaoge.org/images/cloud/RackNerd.png",
  "spartan": "https://icon.xiaoge.org/images/cloud/Spartan.png",
  "v-ps": "https://icon.xiaoge.org/images/cloud/V-PS.png",
  "wawo": "https://icon.xiaoge.org/images/cloud/Wawo.png",
  "herzner": "https://icon.xiaoge.org/images/cloud/herzner.png",
  "netcup": "https://icon.xiaoge.org/images/cloud/netcup.png",
  "serv00": "https://icon.xiaoge.org/images/cloud/serv00.png",
  
  // Docker应用
  "1panel": "https://icon.xiaoge.org/images/docker/1panel.png",
  "1panel-2": "https://icon.xiaoge.org/images/docker/1panel-2.png",
  "1panel-pro": "https://icon.xiaoge.org/images/docker/1panel-Pro.png",
  "adguardhome": "https://icon.xiaoge.org/images/docker/AdguardHome.png",
  "alist": "https://icon.xiaoge.org/images/docker/Alist.png",
  "apache": "https://icon.xiaoge.org/images/docker/Apache.png",
  "bitwarden": "https://icon.xiaoge.org/images/docker/Bitwarden.png",
  "chrome": "https://icon.xiaoge.org/images/docker/Chrome.png",
  "clouddrive": "https://icon.xiaoge.org/images/docker/CloudDrive.png",
  "ddnsto": "https://icon.xiaoge.org/images/docker/DDNSTO.png",
  "dpanel": "https://icon.xiaoge.org/images/docker/DPanel.png",
  "dockercopilot": "https://icon.xiaoge.org/images/docker/DockerCopilot.png",
  "dockercopilot-2": "https://icon.xiaoge.org/images/docker/DockerCopilot-2.png",
  "dockercopilot-3": "https://icon.xiaoge.org/images/docker/DockerCopilot-3.png",
  "dockge": "https://icon.xiaoge.org/images/docker/Dockge.png",
  "draw": "https://icon.xiaoge.org/images/docker/Draw.png",
  "emby": "https://icon.xiaoge.org/images/docker/Emby.png",
  "filebrowser": "https://icon.xiaoge.org/images/docker/FileBrowser.png",
  "flarum": "https://icon.xiaoge.org/images/docker/Flarum.png",
  "grafana": "https://icon.xiaoge.org/images/docker/Grafana.png",
  "hivisionidphotos": "https://icon.xiaoge.org/images/docker/HivisionIDPhotos.png",
  "homeassistant": "https://icon.xiaoge.org/images/docker/HomeAssistant.png",
  "homepage": "https://icon.xiaoge.org/images/docker/HomePage.png",
  "iyuu": "https://icon.xiaoge.org/images/docker/IYUU.png",
  "iyuu-2": "https://icon.xiaoge.org/images/docker/IYUU-2.png",
  "jackett": "https://icon.xiaoge.org/images/docker/Jackett.png",
  "jellyfin": "https://icon.xiaoge.org/images/docker/Jellyfin.png",
  "kms": "https://icon.xiaoge.org/images/docker/KMS.png",
  "kodbox": "https://icon.xiaoge.org/images/docker/KodBox.png",
  "lobechat": "https://icon.xiaoge.org/images/docker/LobeChat.png",
  "lucky": "https://icon.xiaoge.org/images/docker/Lucky.png",
  "lychee": "https://icon.xiaoge.org/images/docker/Lychee.png",
  "mt-photos": "https://icon.xiaoge.org/images/docker/MT-Photos.png",
  "mariadb": "https://icon.xiaoge.org/images/docker/MariaDB.png",
  "mediasaber": "https://icon.xiaoge.org/images/docker/MediaSaber.png",
  "memos": "https://icon.xiaoge.org/images/docker/Memos.png",
  "minio": "https://icon.xiaoge.org/images/docker/MinIO.png",
  "moviepilot": "https://icon.xiaoge.org/images/docker/MoviePilot.png",
  "mysql": "https://icon.xiaoge.org/images/docker/MySQL.png",
  "nastool": "https://icon.xiaoge.org/images/docker/NAStool.png",
  "nastool-2": "https://icon.xiaoge.org/images/docker/NAStool-2.png",
  "npm": "https://icon.xiaoge.org/images/docker/NPM.png",
  "navidrome": "https://icon.xiaoge.org/images/docker/Navidrome.png",
  "nextchat": "https://icon.xiaoge.org/images/docker/NextChat.png",
  "nextcloud": "https://icon.xiaoge.org/images/docker/Nextcloud.png",
  "nginx": "https://icon.xiaoge.org/images/docker/Nginx.png",
  "nginx-2": "https://icon.xiaoge.org/images/docker/Nginx-2.png",
  "ollama": "https://icon.xiaoge.org/images/docker/Ollama.png",
  "openlist": "https://icon.xiaoge.org/images/docker/OpenList.png",
  "openwebui": "https://icon.xiaoge.org/images/docker/OpenWebUI.png",
  "php": "https://icon.xiaoge.org/images/docker/PHP.png",
  "plex": "https://icon.xiaoge.org/images/docker/Plex.png",
  "plex-2": "https://icon.xiaoge.org/images/docker/Plex-2.png",
  "postgresql": "https://icon.xiaoge.org/images/docker/PostgreSQL.png",
  "python": "https://icon.xiaoge.org/images/docker/Python.png",
  "qd": "https://icon.xiaoge.org/images/docker/QD.png",
  "qinglong": "https://icon.xiaoge.org/images/docker/QingLong.png",
  "rustdesk": "https://icon.xiaoge.org/images/docker/RustDesk.png",
  "siyuan": "https://icon.xiaoge.org/images/docker/SiYuan.png",
  "sorayomi": "https://icon.xiaoge.org/images/docker/Sorayomi.png",
  "stirling-pdf": "https://icon.xiaoge.org/images/docker/Stirling-PDF.png",
  "sun-panel": "https://icon.xiaoge.org/images/docker/Sun-Panel.png",
  "tailscale": "https://icon.xiaoge.org/images/docker/Tailscale.png",
  "transmission": "https://icon.xiaoge.org/images/docker/Transmission.png",
  "typecho": "https://icon.xiaoge.org/images/docker/Typecho.png",
  "upsnap": "https://icon.xiaoge.org/images/docker/UpSnap.png",
  "uptimekuma": "https://icon.xiaoge.org/images/docker/UptimeKuma.png",
  "vaultwarden": "https://icon.xiaoge.org/images/docker/Vaultwarden.png",
  "vertex": "https://icon.xiaoge.org/images/docker/Vertex.png",
  "wallos": "https://icon.xiaoge.org/images/docker/Wallos.png",
  "wiki": "https://icon.xiaoge.org/images/docker/Wiki.png",
  "wol": "https://icon.xiaoge.org/images/docker/Wol.png",
  "wordpress": "https://icon.xiaoge.org/images/docker/WordPress.png",
  "wordpress-2": "https://icon.xiaoge.org/images/docker/WordPress-2.png",
  "wordpress-3": "https://icon.xiaoge.org/images/docker/WordPress-3.png",
  "xunlei": "https://icon.xiaoge.org/images/docker/XunLei.png",
  "cookiecloud": "https://icon.xiaoge.org/images/docker/cookiecloud.png",
  "ddnsgo": "https://icon.xiaoge.org/images/docker/ddnsgo.png",
  "dos-lol": "https://icon.xiaoge.org/images/docker/dos-lol.png",
  "flare": "https://icon.xiaoge.org/images/docker/flare.png",
  "frpc": "https://icon.xiaoge.org/images/docker/frpc.png",
  "ftps": "https://icon.xiaoge.org/images/docker/ftps.png",
  "halo": "https://icon.xiaoge.org/images/docker/halo.png",
  "heimdall": "https://icon.xiaoge.org/images/docker/heimdall.png",
  "immich": "https://icon.xiaoge.org/images/docker/immich.png",
  "phpmyadmin": "https://icon.xiaoge.org/images/docker/phpMyAdmin.png",
  "phpmyadmin-2": "https://icon.xiaoge.org/images/docker/phpMyAdmin-2.png",
  "qbittorrent": "https://icon.xiaoge.org/images/docker/qBittorrent.png",
  "tachidesk": "https://icon.xiaoge.org/images/docker/tachidesk.png",
  "wxchat": "https://icon.xiaoge.org/images/docker/wxchat.png",
  
  // NAS系统
  "alpine": "https://icon.xiaoge.org/images/nas/Alpine.png",
  "archlinux": "https://icon.xiaoge.org/images/nas/ArchLinux.png",
  "asustor": "https://icon.xiaoge.org/images/nas/Asustor.png",
  "casaos": "https://icon.xiaoge.org/images/nas/CasaOS.png",
  "centos": "https://icon.xiaoge.org/images/nas/CentOS.png",
  "debian": "https://icon.xiaoge.org/images/nas/Debian.png",
  "debian-2": "https://icon.xiaoge.org/images/nas/Debian-2.png",
  "esxi": "https://icon.xiaoge.org/images/nas/ESXI.png",
  "linkease": "https://icon.xiaoge.org/images/nas/Linkease.png",
  "linux": "https://icon.xiaoge.org/images/nas/Linux.png",
  "macos": "https://icon.xiaoge.org/images/nas/MacOS.png",
  "omv": "https://icon.xiaoge.org/images/nas/OMV.png",
  "openwrt": "https://icon.xiaoge.org/images/nas/OpenWrt.png",
  "pve": "https://icon.xiaoge.org/images/nas/PVE.png",
  "qts": "https://icon.xiaoge.org/images/nas/QTS.png",
  "synology": "https://icon.xiaoge.org/images/nas/Synology.png",
  "tos": "https://icon.xiaoge.org/images/nas/TOS.png",
  "truenas": "https://icon.xiaoge.org/images/nas/TrueNAS.png",
  "ugos": "https://icon.xiaoge.org/images/nas/UGOS.png",
  "ugos-pro": "https://icon.xiaoge.org/images/nas/UGOS-PRO.png",
  "unraid": "https://icon.xiaoge.org/images/nas/UNRAID.png",
  "unraid-2": "https://icon.xiaoge.org/images/nas/UNRAID-2.png",
  "unraid-3": "https://icon.xiaoge.org/images/nas/UNRAID-3.png",
  "ubuntu": "https://icon.xiaoge.org/images/nas/Ubuntu.png",
  "vmware": "https://icon.xiaoge.org/images/nas/Vmware.png",
  "winserver": "https://icon.xiaoge.org/images/nas/WinServer.png",
  "windows10": "https://icon.xiaoge.org/images/nas/Windows10.png",
  "windows11": "https://icon.xiaoge.org/images/nas/Windows11.png",
  "windows7": "https://icon.xiaoge.org/images/nas/Windows7.png",
  "zimaos": "https://icon.xiaoge.org/images/nas/ZimaOS.png",
  "zspace": "https://icon.xiaoge.org/images/nas/Zspace.png",
  "fnos": "https://icon.xiaoge.org/images/nas/fnOS.png",
  "ikuai": "https://icon.xiaoge.org/images/nas/iKuai.png",
  "istoreos": "https://icon.xiaoge.org/images/nas/iStoreOS.png",
  
  // PT站点
  "audiences": "https://icon.xiaoge.org/images/pt/Audiences.png",
  "chdbits": "https://icon.xiaoge.org/images/pt/CHDbits.png",
  "frds": "https://icon.xiaoge.org/images/pt/FRDS.png",
  "fsm": "https://icon.xiaoge.org/images/pt/FSM.png",
  "hdchina": "https://icon.xiaoge.org/images/pt/HDChina.png",
  "hdhome": "https://icon.xiaoge.org/images/pt/HDHome.png",
  "hdsky": "https://icon.xiaoge.org/images/pt/HDsky.png",
  "hhclub": "https://icon.xiaoge.org/images/pt/HHCLUB.png",
  "m-team": "https://icon.xiaoge.org/images/pt/M-Team.png",
  "nvme": "https://icon.xiaoge.org/images/pt/Nvme.png",
  "opencd": "https://icon.xiaoge.org/images/pt/OpenCD.png",
  "ourbits": "https://icon.xiaoge.org/images/pt/OurBits.png",
  "pthome": "https://icon.xiaoge.org/images/pt/PTHOME.png",
  "pttime": "https://icon.xiaoge.org/images/pt/PTTime.png",
  "pter": "https://icon.xiaoge.org/images/pt/Pter.png",
  "ttg": "https://icon.xiaoge.org/images/pt/TTG.png",
  "ubits": "https://icon.xiaoge.org/images/pt/UBits.png",
  "agsv": "https://icon.xiaoge.org/images/pt/agsv.png",
  "btschool": "https://icon.xiaoge.org/images/pt/btschool.png",
  "carpt": "https://icon.xiaoge.org/images/pt/carpt.png",
  "cyanbug": "https://icon.xiaoge.org/images/pt/cyanbug.png",
  "dajiao": "https://icon.xiaoge.org/images/pt/dajiao.png",
  "dicmusic": "https://icon.xiaoge.org/images/pt/dicmusic.png",
  "discfan": "https://icon.xiaoge.org/images/pt/discfan.png",
  "gpw": "https://icon.xiaoge.org/images/pt/gpw.png",
  "haidan": "https://icon.xiaoge.org/images/pt/haidan.png",
  "hdarea": "https://icon.xiaoge.org/images/pt/hdarea.png",
  "hddolby": "https://icon.xiaoge.org/images/pt/hddolby.png",
  "hdfans": "https://icon.xiaoge.org/images/pt/hdfans.png",
  "hdkyl": "https://icon.xiaoge.org/images/pt/hdkyl.png",
  "hdvideo": "https://icon.xiaoge.org/images/pt/hdvideo.png",
  "icc2022": "https://icon.xiaoge.org/images/pt/icc2022.png",
  "leaves": "https://icon.xiaoge.org/images/pt/leaves.png",
  "lemonhd": "https://icon.xiaoge.org/images/pt/lemonhd.png",
  "nicept": "https://icon.xiaoge.org/images/pt/nicept.png",
  "panda": "https://icon.xiaoge.org/images/pt/panda.png",
  "ptsbao": "https://icon.xiaoge.org/images/pt/ptsbao.png",
  "ptvicomo": "https://icon.xiaoge.org/images/pt/ptvicomo.png",
  "qingwapt": "https://icon.xiaoge.org/images/pt/qingwapt.png",
  "rousi": "https://icon.xiaoge.org/images/pt/rousi.png",
  "soulvoice": "https://icon.xiaoge.org/images/pt/soulvoice.png",
  "tjupt": "https://icon.xiaoge.org/images/pt/tjupt.png",
  "xingtan": "https://icon.xiaoge.org/images/pt/xingtan.png",
  "ying": "https://icon.xiaoge.org/images/pt/ying.png",
  "zhuque": "https://icon.xiaoge.org/images/pt/zhuque.png",
  "zmpt": "https://icon.xiaoge.org/images/pt/zmpt.png",
  
  // 网站服务
  "115": "https://icon.xiaoge.org/images/website/115.png",
  "115-2": "https://icon.xiaoge.org/images/website/115-2.png",
  "123": "https://icon.xiaoge.org/images/website/123.png",
  "ai-studio": "https://icon.xiaoge.org/images/website/AI-Studio.png",
  "bt": "https://icon.xiaoge.org/images/website/BT.png",
  "bt-2": "https://icon.xiaoge.org/images/website/BT-2.png",
  "backblaze": "https://icon.xiaoge.org/images/website/Backblaze.png",
  "bilibili": "https://icon.xiaoge.org/images/website/BiliBili.png",
  "chatgpt": "https://icon.xiaoge.org/images/website/ChatGPT.png",
  "chatgpt-2": "https://icon.xiaoge.org/images/website/ChatGPT-2.png",
  "cloudflare": "https://icon.xiaoge.org/images/website/CloudFlare.png",
  "copyleaks": "https://icon.xiaoge.org/images/website/Copyleaks.png",
  "creativefabrica": "https://icon.xiaoge.org/images/website/Creativefabrica.png",
  "deepseek": "https://icon.xiaoge.org/images/website/DeepSeek.png",
  "docker": "https://icon.xiaoge.org/images/website/Docker.png",
  "dockerapps": "https://icon.xiaoge.org/images/website/DockerApps.png",
  "flowus": "https://icon.xiaoge.org/images/website/Flowus.png",
  "follow": "https://icon.xiaoge.org/images/website/Follow.png",
  "gemini": "https://icon.xiaoge.org/images/website/Gemini.png",
  "github": "https://icon.xiaoge.org/images/website/GitHub.png",
  "github-2": "https://icon.xiaoge.org/images/website/GitHub-2.png",
  "google": "https://icon.xiaoge.org/images/website/Google.png",
  "googlesearch": "https://icon.xiaoge.org/images/website/GoogleSearch.png",
  "grok": "https://icon.xiaoge.org/images/website/Grok.png",
  "hkvps": "https://icon.xiaoge.org/images/website/HKVPS.png",
  "hostloc": "https://icon.xiaoge.org/images/website/Hostloc.png",
  "koolcenter": "https://icon.xiaoge.org/images/website/KoolCenter.png",
  "makerworld": "https://icon.xiaoge.org/images/website/MakerWorld.png",
  "mastergo": "https://icon.xiaoge.org/images/website/MasterGo.png",
  "ng": "https://icon.xiaoge.org/images/website/NG.png",
  "nazhumi": "https://icon.xiaoge.org/images/website/Nazhumi.png",
  "nezha": "https://icon.xiaoge.org/images/website/Nezha.png",
  "nodeseek": "https://icon.xiaoge.org/images/website/NodeSeek.png",
  "notion": "https://icon.xiaoge.org/images/website/Notion.png",
  "pexels": "https://icon.xiaoge.org/images/website/Pexels.png",
  "pinterest": "https://icon.xiaoge.org/images/website/Pinterest.png"
};

// 获取镜像的logo URL
// 优先级: 用户自定义 > 内置logo > 默认图标
export const getImageLogo = (imageName, customLogos = {}) => {
  // 先检查用户自定义的logo
  if (customLogos[imageName]) {
    return customLogos[imageName];
  }
  
  // 检查内置logo
  const baseImageName = imageName.split(':')[0]; // 去掉tag部分
  if (builtInImageLogos[baseImageName]) {
    return builtInImageLogos[baseImageName];
  }
  
  // 没有找到logo，返回null
  return null;
};

// 获取所有支持的镜像名称列表
export const getSupportedImageNames = () => {
  return Object.keys(builtInImageLogos);
};

// 检查镜像是否有内置logo
export const hasBuiltInLogo = (imageName) => {
  const baseImageName = imageName.split(':')[0];
  return builtInImageLogos[baseImageName] !== undefined;
};